apiVersion: apps/v1
kind: Deployment
metadata:
  name: low
spec:
  replicas: 1
  selector:
    matchLabels:
      app: low
  template:
    metadata:
      labels:
        app: low
    spec:
      containers:
      - image: okteto.dev/low:latest
        name: low
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "8e23b1d2-5d5f-4272-8cc3-be9d74014f2d"
        - name: Vless_Path
          value: "/6usnJscs"
        - name: Vmess_UUID
          value: "8e23b1d2-5d5f-4272-8cc3-be9d74014f2d"
        - name: Vmess_Path
          value: "/op9kms"
        - name: Share_Path
          value: "/Share233"
